version: '3.8'
# Services
services:
  # Traefik Service
  traefik:
    image: traefik:$TRAEFIK_VERSION
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - $baseDir/docker/traefik/etc:/etc/traefik:ro
      - $baseDir/mnt/var/log/traefik:/var/log
    networks:
      - splunk