version: '3.8'
# Services
services:
  # Splunk Service
  splunk:
    image: splunk/splunk
    container_name: splunk
    restart: always
    cap_add: ['IPC_LOCK']
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_APPS_URL: https://github.com/lluked/cowrie-splunk-app/archive/main.tar.gz
      SPLUNK_PASSWORD: $SPLUNK_PASSWORD
    volumes:
      - $baseDir/docker/splunk/opt/splunk/etc/system/local/limits.conf:/opt/splunk/etc/system/local/limits.conf:ro
      - $baseDir/docker/splunk/opt/splunk/etc/system/local/web.conf:/opt/splunk/etc/system/local/web.conf:ro
      - $baseDir/opt/splunk/etc/apps/cowrie-splunk-app-main/local/inputs.conf:/opt/splunk/etc/apps/cowrie-splunk-app-main/local/inputs.conf:ro
      - $baseDir/mnt/var/log/honeypot:/var/log/honeypot:ro
    # ports:
    #   - "8000:8000"
    networks:
      - splunk
# Networks
networks:
  # Splunk Network
  splunk: