---

- name: Update apt-cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: yes
