version: '3.8'
# Services
services:
  # Cowrie Service
  cowrie:
    build:
      context: $baseDir/docker/honeypot/cowrie/
      dockerfile: Dockerfile
      args:
        COWRIE_VERSION: $COWRIE_VERSION
    container_name: cowrie
    restart: always
    ports:
      - "22:2222"
      - "23:2223"
    volumes:
      - $baseDir/docker/honeypot/cowrie/etc/cowrie.cfg:/home/cowrie/cowrie/etc/cowrie.cfg:ro
      - $baseDir/docker/honeypot/cowrie/etc/userdb.txt:/home/cowrie/cowrie/etc/userdb.txt:ro
      - $baseDir/mnt/var/log/honeypot/cowrie:/home/cowrie/cowrie/var/log
      - $baseDir/mnt/var/data/honeypot/cowrie/dl:/home/cowrie/cowrie/var/dl
      - $baseDir/mnt/var/data/honeypot/cowrie/tty:/home/cowrie/cowrie/var/tty
    networks:
      - cowrie
# Networks
networks:
    # Cowrie Network
    cowrie: